### PR TITLE
[Working Fireplace] Converted to Harmony patch for Android compatibility

### PR DESCRIPTION
**Pull request by Jonqora**
Hello! The previous version did not work on Android devices due to input differences (no ability for IsUseToolButton and IsActionButton checks). Instead of relying on Input.ButtonPressed events, I've rewritten this code as a Harmony patch to intervene directly at Furniture.checkForAction.

I have tested the new code on Android and PC. The only change in previous behavior is that fireplaces can no longer be turned off in the usual way (this is to avoid accidental clicks on Android). You can still turn a fireplace off at any time by moving it (left-click).

### CODE REVIEW

**Comment by jahangmar** [comment]
Hi, thank you for writing this patch. While I appreciate your work, there are two reasons I won't use your code:
1. I don't use harmony since it creates compatibility issues. I don't like how it works.
2. I don't use Stardew Valley on Android and I can't maintain software that I cannot test.

You could upload your own version and I can link to it on the mod page. If you don't want to do this, I could figure out how to make a second build of the mod that uses the harmony patch and upload it as an optional/alternative file. In both cases, I won't be able to test the android version and this might be an issue for future updates.

**Comment by Jonqora** [comment]
Fair enough! I created the patch primarily for my own use, but it would be great to also make it easily available to other android users.

I don't really want to make a new page for the changed version - I wouldn't want to divert attention from your work or maintain a mod page for work that isn't my own. You have my permission to make the harmony verison available as an optional/alternative download for this and for any future updates I might make a patch for.

May I suggest that you create a new "android-harmony" branch on your repo? I can submit new PRs to that branch while pulling from master upstream for future updates.

**Comment by jahangmar** [comment]
I integrated your code into the mod by using preprocessor directives. This allows me to have only one file instead of different versions. The harmony version seems to work perfectly on my system. Thank you again for the effort.
It's also uploaded to the nexus mod page.

**Comment by Jonqora** [comment]
I took some time today to learn about pre-processor directives and how they work. Now I have an even greater appreciation for your solution because I can understand it! Thanks again for incorporating this. :)

**Pull request closed without merging**
